---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hashdigitec/tower.web.hashdigitech.com/
    - /bin/cp * $DEPLOYPATH
    - /bin/cp/css * $DEPLOYPATH
    - /bin/cp/images * $DEPLOYPATH 
    - /bin/cp/fonts * $DEPLOYPATH
    - /bin/cp/js * $DEPLOYPATH
